# Generated by Django 5.0 on 2024-01-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitts', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
